feat(uploader): ajv json schema validation
ajv json schema validation
Not using https://api.prts.plus/static/maa-copilot-schema.json due to
error: can't resolve reference #/definitions/stage_name